# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blob.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blob.proto',
  package='blob',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\nblob.proto\x12\x04\x62lob\"/\n\x0b\x42lobRequest\x12\n\n\x02id\x18\x01 \x01(\r\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\"`\n\x0c\x42lobResponse\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\r\n\x05\x61live\x18\x03 \x01(\x08\x12\x0c\n\x04mass\x18\x04 \x01(\x05\x12\x0f\n\x07players\x18\x05 \x01(\x0c\x12\x0c\n\x04\x66ood\x18\x06 \x01(\x0c\x32\x37\n\x04\x42lob\x12/\n\x04Move\x12\x11.blob.BlobRequest\x1a\x12.blob.BlobResponse\"\x00\x62\x06proto3'
)




_BLOBREQUEST = _descriptor.Descriptor(
  name='BlobRequest',
  full_name='blob.BlobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='blob.BlobRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='blob.BlobRequest.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='blob.BlobRequest.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=67,
)


_BLOBRESPONSE = _descriptor.Descriptor(
  name='BlobResponse',
  full_name='blob.BlobResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='blob.BlobResponse.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='blob.BlobResponse.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alive', full_name='blob.BlobResponse.alive', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mass', full_name='blob.BlobResponse.mass', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='players', full_name='blob.BlobResponse.players', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='food', full_name='blob.BlobResponse.food', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['BlobRequest'] = _BLOBREQUEST
DESCRIPTOR.message_types_by_name['BlobResponse'] = _BLOBRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlobRequest = _reflection.GeneratedProtocolMessageType('BlobRequest', (_message.Message,), {
  'DESCRIPTOR' : _BLOBREQUEST,
  '__module__' : 'blob_pb2'
  # @@protoc_insertion_point(class_scope:blob.BlobRequest)
  })
_sym_db.RegisterMessage(BlobRequest)

BlobResponse = _reflection.GeneratedProtocolMessageType('BlobResponse', (_message.Message,), {
  'DESCRIPTOR' : _BLOBRESPONSE,
  '__module__' : 'blob_pb2'
  # @@protoc_insertion_point(class_scope:blob.BlobResponse)
  })
_sym_db.RegisterMessage(BlobResponse)



_BLOB = _descriptor.ServiceDescriptor(
  name='Blob',
  full_name='blob.Blob',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=167,
  serialized_end=222,
  methods=[
  _descriptor.MethodDescriptor(
    name='Move',
    full_name='blob.Blob.Move',
    index=0,
    containing_service=None,
    input_type=_BLOBREQUEST,
    output_type=_BLOBRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLOB)

DESCRIPTOR.services_by_name['Blob'] = _BLOB

# @@protoc_insertion_point(module_scope)
