// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/region.proto

/*
Package region is a generated protocol buffer package.

It is generated from these files:
	server/region.proto

It has these top-level messages:
	PingRequest
	PingResponse
*/
package region

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PingResponse struct {
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*PingRequest)(nil), "region.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "region.PingResponse")
}

func init() { proto.RegisterFile("server/region.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2f, 0x4a, 0x4d, 0xcf, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x83, 0xf0, 0x94, 0x78, 0xb9, 0xb8, 0x03, 0x32, 0xf3, 0xd2, 0x83, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0x94, 0xf8, 0xb8, 0x78, 0x20, 0xdc, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x23, 0x5b,
	0x2e, 0xb6, 0x20, 0xb0, 0x42, 0x21, 0x63, 0x2e, 0x16, 0x90, 0x8c, 0x90, 0xb0, 0x1e, 0xd4, 0x1c,
	0x24, 0x6d, 0x52, 0x22, 0xa8, 0x82, 0x10, 0xcd, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0xcb, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x81, 0xd9, 0xcc, 0x83, 0x00, 0x00, 0x00,
}
