// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Blob struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	X                    float64  `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Alive                bool     `protobuf:"varint,4,opt,name=alive,proto3" json:"alive,omitempty"`
	Mass                 int32    `protobuf:"varint,5,opt,name=mass,proto3" json:"mass,omitempty"`
	Ver                  int32    `protobuf:"varint,6,opt,name=ver,proto3" json:"ver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blob) Reset()         { *m = Blob{} }
func (m *Blob) String() string { return proto.CompactTextString(m) }
func (*Blob) ProtoMessage()    {}
func (*Blob) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Blob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blob.Unmarshal(m, b)
}
func (m *Blob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blob.Marshal(b, m, deterministic)
}
func (m *Blob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blob.Merge(m, src)
}
func (m *Blob) XXX_Size() int {
	return xxx_messageInfo_Blob.Size(m)
}
func (m *Blob) XXX_DiscardUnknown() {
	xxx_messageInfo_Blob.DiscardUnknown(m)
}

var xxx_messageInfo_Blob proto.InternalMessageInfo

func (m *Blob) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Blob) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Blob) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Blob) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

func (m *Blob) GetMass() int32 {
	if m != nil {
		return m.Mass
	}
	return 0
}

func (m *Blob) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

type Food struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Food) Reset()         { *m = Food{} }
func (m *Food) String() string { return proto.CompactTextString(m) }
func (*Food) ProtoMessage()    {}
func (*Food) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Food) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Food.Unmarshal(m, b)
}
func (m *Food) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Food.Marshal(b, m, deterministic)
}
func (m *Food) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Food.Merge(m, src)
}
func (m *Food) XXX_Size() int {
	return xxx_messageInfo_Food.Size(m)
}
func (m *Food) XXX_DiscardUnknown() {
	xxx_messageInfo_Food.DiscardUnknown(m)
}

var xxx_messageInfo_Food proto.InternalMessageInfo

func (m *Food) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Food) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*Blob)(nil), "common.Blob")
	proto.RegisterType((*Food)(nil), "common.Food")
}

func init() {
	proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206)
}

var fileDescriptor_555bd8c177793206 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xf2, 0xb8, 0x58,
	0x9c, 0x72, 0xf2, 0x93, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x0b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0x98, 0x32, 0x0b, 0x84, 0x78, 0xb8, 0x18, 0x2b, 0x24, 0x98, 0x14, 0x18, 0x35, 0x18, 0x83,
	0x18, 0x2b, 0x40, 0xbc, 0x4a, 0x09, 0x66, 0x08, 0xaf, 0x52, 0x48, 0x84, 0x8b, 0x35, 0x31, 0x27,
	0xb3, 0x2c, 0x55, 0x82, 0x45, 0x81, 0x51, 0x83, 0x23, 0x08, 0xc2, 0x11, 0x12, 0xe2, 0x62, 0xc9,
	0x4d, 0x2c, 0x2e, 0x96, 0x60, 0x55, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0xb3, 0x85, 0x04, 0xb8, 0x98,
	0xcb, 0x52, 0x8b, 0x24, 0xd8, 0xc0, 0x42, 0x20, 0xa6, 0x92, 0x12, 0x17, 0x8b, 0x5b, 0x7e, 0x7e,
	0x0a, 0xc4, 0x7c, 0x46, 0x14, 0xf3, 0xa1, 0xb6, 0x55, 0x26, 0xb1, 0x81, 0x9d, 0x68, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x73, 0x1d, 0xcf, 0x46, 0xb2, 0x00, 0x00, 0x00,
}
