// Code generated by protoc-gen-go. DO NOT EDIT.
// source: player.proto

/*
Package player is a generated protocol buffer package.

It is generated from these files:
	player.proto

It has these top-level messages:
	InitRequest
	InitResponse
	MoveRequest
	MoveResponse
	RegionRequest
	RegionResponse
	Blob
	Food
*/
package player

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InitRequest struct {
}

func (m *InitRequest) Reset()                    { *m = InitRequest{} }
func (m *InitRequest) String() string            { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()               {}
func (*InitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type InitResponse struct {
	Id   string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	X    float64 `protobuf:"fixed64,2,opt,name=x" json:"x,omitempty"`
	Y    float64 `protobuf:"fixed64,3,opt,name=y" json:"y,omitempty"`
	Mass int32   `protobuf:"varint,4,opt,name=mass" json:"mass,omitempty"`
}

func (m *InitResponse) Reset()                    { *m = InitResponse{} }
func (m *InitResponse) String() string            { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()               {}
func (*InitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InitResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InitResponse) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *InitResponse) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *InitResponse) GetMass() int32 {
	if m != nil {
		return m.Mass
	}
	return 0
}

type MoveRequest struct {
	Id string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	X  float64 `protobuf:"fixed64,2,opt,name=x" json:"x,omitempty"`
	Y  float64 `protobuf:"fixed64,3,opt,name=y" json:"y,omitempty"`
}

func (m *MoveRequest) Reset()                    { *m = MoveRequest{} }
func (m *MoveRequest) String() string            { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()               {}
func (*MoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MoveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MoveRequest) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MoveRequest) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type MoveResponse struct {
	X     float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y     float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
	Alive bool    `protobuf:"varint,3,opt,name=alive" json:"alive,omitempty"`
	Mass  int32   `protobuf:"varint,4,opt,name=mass" json:"mass,omitempty"`
}

func (m *MoveResponse) Reset()                    { *m = MoveResponse{} }
func (m *MoveResponse) String() string            { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()               {}
func (*MoveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MoveResponse) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MoveResponse) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *MoveResponse) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

func (m *MoveResponse) GetMass() int32 {
	if m != nil {
		return m.Mass
	}
	return 0
}

type RegionRequest struct {
	X float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
}

func (m *RegionRequest) Reset()                    { *m = RegionRequest{} }
func (m *RegionRequest) String() string            { return proto.CompactTextString(m) }
func (*RegionRequest) ProtoMessage()               {}
func (*RegionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RegionRequest) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *RegionRequest) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type RegionResponse struct {
	Blobs []*Blob `protobuf:"bytes,1,rep,name=blobs" json:"blobs,omitempty"`
	Foods []*Food `protobuf:"bytes,2,rep,name=foods" json:"foods,omitempty"`
}

func (m *RegionResponse) Reset()                    { *m = RegionResponse{} }
func (m *RegionResponse) String() string            { return proto.CompactTextString(m) }
func (*RegionResponse) ProtoMessage()               {}
func (*RegionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RegionResponse) GetBlobs() []*Blob {
	if m != nil {
		return m.Blobs
	}
	return nil
}

func (m *RegionResponse) GetFoods() []*Food {
	if m != nil {
		return m.Foods
	}
	return nil
}

type Blob struct {
	String_ string  `protobuf:"bytes,1,opt,name=string" json:"string,omitempty"`
	X       float64 `protobuf:"fixed64,2,opt,name=x" json:"x,omitempty"`
	Y       float64 `protobuf:"fixed64,3,opt,name=y" json:"y,omitempty"`
	Alive   bool    `protobuf:"varint,4,opt,name=alive" json:"alive,omitempty"`
	Mass    int32   `protobuf:"varint,5,opt,name=mass" json:"mass,omitempty"`
}

func (m *Blob) Reset()                    { *m = Blob{} }
func (m *Blob) String() string            { return proto.CompactTextString(m) }
func (*Blob) ProtoMessage()               {}
func (*Blob) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Blob) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func (m *Blob) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Blob) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Blob) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

func (m *Blob) GetMass() int32 {
	if m != nil {
		return m.Mass
	}
	return 0
}

type Food struct {
	X float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
}

func (m *Food) Reset()                    { *m = Food{} }
func (m *Food) String() string            { return proto.CompactTextString(m) }
func (*Food) ProtoMessage()               {}
func (*Food) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Food) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Food) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*InitRequest)(nil), "player.InitRequest")
	proto.RegisterType((*InitResponse)(nil), "player.InitResponse")
	proto.RegisterType((*MoveRequest)(nil), "player.MoveRequest")
	proto.RegisterType((*MoveResponse)(nil), "player.MoveResponse")
	proto.RegisterType((*RegionRequest)(nil), "player.RegionRequest")
	proto.RegisterType((*RegionResponse)(nil), "player.RegionResponse")
	proto.RegisterType((*Blob)(nil), "player.Blob")
	proto.RegisterType((*Food)(nil), "player.Food")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Player service

type PlayerClient interface {
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error)
	Region(ctx context.Context, in *RegionRequest, opts ...grpc.CallOption) (*RegionResponse, error)
}

type playerClient struct {
	cc *grpc.ClientConn
}

func NewPlayerClient(cc *grpc.ClientConn) PlayerClient {
	return &playerClient{cc}
}

func (c *playerClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	out := new(InitResponse)
	err := grpc.Invoke(ctx, "/player.Player/Init", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := grpc.Invoke(ctx, "/player.Player/Move", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) Region(ctx context.Context, in *RegionRequest, opts ...grpc.CallOption) (*RegionResponse, error) {
	out := new(RegionResponse)
	err := grpc.Invoke(ctx, "/player.Player/Region", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Player service

type PlayerServer interface {
	Init(context.Context, *InitRequest) (*InitResponse, error)
	Move(context.Context, *MoveRequest) (*MoveResponse, error)
	Region(context.Context, *RegionRequest) (*RegionResponse, error)
}

func RegisterPlayerServer(s *grpc.Server, srv PlayerServer) {
	s.RegisterService(&_Player_serviceDesc, srv)
}

func _Player_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player.Player/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player.Player/Move",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).Move(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_Region_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).Region(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player.Player/Region",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).Region(ctx, req.(*RegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Player_serviceDesc = grpc.ServiceDesc{
	ServiceName: "player.Player",
	HandlerType: (*PlayerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Player_Init_Handler,
		},
		{
			MethodName: "Move",
			Handler:    _Player_Move_Handler,
		},
		{
			MethodName: "Region",
			Handler:    _Player_Region_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "player.proto",
}

func init() { proto.RegisterFile("player.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x5d, 0xba, 0xb4, 0xe8, 0xb7, 0x6e, 0x87, 0x38, 0x47, 0xd8, 0xa9, 0xe4, 0x54, 0x10, 0x76,
	0xd8, 0x4e, 0xbb, 0x7a, 0x10, 0x3c, 0x28, 0x12, 0x3c, 0x78, 0x5d, 0x69, 0x1c, 0x81, 0xda, 0xcc,
	0xa6, 0x8e, 0xf5, 0x47, 0xf9, 0x1f, 0x25, 0x4d, 0xe2, 0x5a, 0x19, 0x05, 0x6f, 0x7d, 0xcd, 0x7b,
	0x5f, 0xde, 0xf7, 0x5e, 0x20, 0x3e, 0x14, 0xbb, 0x46, 0x54, 0xab, 0x43, 0xa5, 0x6a, 0x45, 0x22,
	0x8b, 0xd8, 0x14, 0x26, 0x8f, 0xa5, 0xac, 0xb9, 0xf8, 0xfc, 0x12, 0xba, 0x66, 0xcf, 0x10, 0x5b,
	0xa8, 0x0f, 0xaa, 0xd4, 0x82, 0xcc, 0x20, 0x90, 0x39, 0x45, 0x09, 0x4a, 0xaf, 0x79, 0x20, 0x73,
	0x12, 0x03, 0x3a, 0xd1, 0x20, 0x41, 0x29, 0xe2, 0xe8, 0x64, 0x50, 0x43, 0xc7, 0x16, 0x35, 0x84,
	0x00, 0xfe, 0xd8, 0x69, 0x4d, 0x71, 0x82, 0xd2, 0x90, 0xb7, 0xdf, 0x6c, 0x0b, 0x93, 0x27, 0x75,
	0x14, 0x6e, 0xfc, 0x7f, 0xc6, 0xb1, 0x57, 0x88, 0xad, 0xd4, 0x59, 0x69, 0xb9, 0xa8, 0xc7, 0x0d,
	0xfc, 0xd5, 0x73, 0x08, 0x77, 0x85, 0x3c, 0x8a, 0x56, 0x7d, 0xc5, 0x2d, 0xb8, 0x68, 0xe8, 0x0e,
	0xa6, 0x5c, 0xec, 0xa5, 0x2a, 0xbd, 0xa5, 0x81, 0xb1, 0xec, 0x0d, 0x66, 0x9e, 0xec, 0x4c, 0x30,
	0x08, 0xb3, 0x42, 0x65, 0x9a, 0xa2, 0x64, 0x9c, 0x4e, 0xd6, 0xf1, 0xca, 0x85, 0x7a, 0x5f, 0xa8,
	0x8c, 0xdb, 0x23, 0xc3, 0x79, 0x57, 0x2a, 0xd7, 0x34, 0xe8, 0x73, 0x1e, 0x94, 0xca, 0xb9, 0x3d,
	0x62, 0x39, 0x60, 0x23, 0x21, 0x0b, 0x88, 0x74, 0x5d, 0xc9, 0x72, 0xef, 0x42, 0x71, 0x68, 0x30,
	0xe7, 0xdf, 0x65, 0xf1, 0xa5, 0x65, 0xc3, 0xce, 0xb2, 0x0c, 0xb0, 0xb9, 0x74, 0x68, 0xc7, 0xf5,
	0x37, 0x82, 0xe8, 0xa5, 0x35, 0x48, 0x36, 0x80, 0x4d, 0xf9, 0xe4, 0xc6, 0x3b, 0xee, 0xbc, 0x8c,
	0xe5, 0xbc, 0xff, 0xd3, 0xe6, 0xc1, 0x46, 0x46, 0x64, 0x6a, 0x3a, 0x8b, 0x3a, 0x7d, 0x9f, 0x45,
	0xdd, 0x26, 0xd9, 0x88, 0x6c, 0x21, 0xb2, 0xc1, 0x92, 0x5b, 0xcf, 0xe8, 0xb5, 0xb2, 0x5c, 0xfc,
	0xfd, 0xed, 0xa5, 0x59, 0xd4, 0xbe, 0xdf, 0xcd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x67, 0x11,
	0xab, 0x53, 0xcf, 0x02, 0x00, 0x00,
}
