// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/player.proto

/*
Package player is a generated protocol buffer package.

It is generated from these files:
	server/player.proto

It has these top-level messages:
	InitRequest
	InitResponse
	MoveRequest
	MoveResponse
	RegionRequest
	RegionResponse
	Blob
	Food
*/
package player

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InitRequest struct {
}

func (m *InitRequest) Reset()                    { *m = InitRequest{} }
func (m *InitRequest) String() string            { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()               {}
func (*InitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type InitResponse struct {
	Id   string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	X    float64 `protobuf:"fixed64,2,opt,name=x" json:"x,omitempty"`
	Y    float64 `protobuf:"fixed64,3,opt,name=y" json:"y,omitempty"`
	Mass int32   `protobuf:"varint,4,opt,name=mass" json:"mass,omitempty"`
}

func (m *InitResponse) Reset()                    { *m = InitResponse{} }
func (m *InitResponse) String() string            { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()               {}
func (*InitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InitResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InitResponse) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *InitResponse) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *InitResponse) GetMass() int32 {
	if m != nil {
		return m.Mass
	}
	return 0
}

type MoveRequest struct {
	Id string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	X  float64 `protobuf:"fixed64,2,opt,name=x" json:"x,omitempty"`
	Y  float64 `protobuf:"fixed64,3,opt,name=y" json:"y,omitempty"`
}

func (m *MoveRequest) Reset()                    { *m = MoveRequest{} }
func (m *MoveRequest) String() string            { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()               {}
func (*MoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MoveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MoveRequest) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MoveRequest) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type MoveResponse struct {
	X     float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y     float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
	Alive bool    `protobuf:"varint,3,opt,name=alive" json:"alive,omitempty"`
	Mass  int32   `protobuf:"varint,4,opt,name=mass" json:"mass,omitempty"`
}

func (m *MoveResponse) Reset()                    { *m = MoveResponse{} }
func (m *MoveResponse) String() string            { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()               {}
func (*MoveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MoveResponse) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MoveResponse) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *MoveResponse) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

func (m *MoveResponse) GetMass() int32 {
	if m != nil {
		return m.Mass
	}
	return 0
}

type RegionRequest struct {
	X float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
}

func (m *RegionRequest) Reset()                    { *m = RegionRequest{} }
func (m *RegionRequest) String() string            { return proto.CompactTextString(m) }
func (*RegionRequest) ProtoMessage()               {}
func (*RegionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RegionRequest) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *RegionRequest) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type RegionResponse struct {
	Blobs []*Blob `protobuf:"bytes,1,rep,name=blobs" json:"blobs,omitempty"`
	Foods []*Food `protobuf:"bytes,2,rep,name=foods" json:"foods,omitempty"`
}

func (m *RegionResponse) Reset()                    { *m = RegionResponse{} }
func (m *RegionResponse) String() string            { return proto.CompactTextString(m) }
func (*RegionResponse) ProtoMessage()               {}
func (*RegionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RegionResponse) GetBlobs() []*Blob {
	if m != nil {
		return m.Blobs
	}
	return nil
}

func (m *RegionResponse) GetFoods() []*Food {
	if m != nil {
		return m.Foods
	}
	return nil
}

type Blob struct {
	String_ string  `protobuf:"bytes,1,opt,name=string" json:"string,omitempty"`
	X       float64 `protobuf:"fixed64,2,opt,name=x" json:"x,omitempty"`
	Y       float64 `protobuf:"fixed64,3,opt,name=y" json:"y,omitempty"`
	Alive   bool    `protobuf:"varint,4,opt,name=alive" json:"alive,omitempty"`
	Mass    int32   `protobuf:"varint,5,opt,name=mass" json:"mass,omitempty"`
}

func (m *Blob) Reset()                    { *m = Blob{} }
func (m *Blob) String() string            { return proto.CompactTextString(m) }
func (*Blob) ProtoMessage()               {}
func (*Blob) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Blob) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func (m *Blob) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Blob) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Blob) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

func (m *Blob) GetMass() int32 {
	if m != nil {
		return m.Mass
	}
	return 0
}

type Food struct {
	X float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
}

func (m *Food) Reset()                    { *m = Food{} }
func (m *Food) String() string            { return proto.CompactTextString(m) }
func (*Food) ProtoMessage()               {}
func (*Food) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Food) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Food) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*InitRequest)(nil), "player.InitRequest")
	proto.RegisterType((*InitResponse)(nil), "player.InitResponse")
	proto.RegisterType((*MoveRequest)(nil), "player.MoveRequest")
	proto.RegisterType((*MoveResponse)(nil), "player.MoveResponse")
	proto.RegisterType((*RegionRequest)(nil), "player.RegionRequest")
	proto.RegisterType((*RegionResponse)(nil), "player.RegionResponse")
	proto.RegisterType((*Blob)(nil), "player.Blob")
	proto.RegisterType((*Food)(nil), "player.Food")
}

func init() { proto.RegisterFile("server/player.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x5d, 0xba, 0xb4, 0xe8, 0xb7, 0x6e, 0x87, 0x6c, 0x8e, 0xb0, 0x53, 0xc9, 0xa9, 0x20, 0x4c,
	0xd8, 0x4e, 0xbb, 0x7a, 0x10, 0x3c, 0x28, 0x12, 0x3c, 0x78, 0x5d, 0x69, 0x1c, 0x81, 0xda, 0xcc,
	0xa6, 0x8e, 0xed, 0x47, 0xf9, 0x1f, 0x25, 0x4d, 0xe2, 0x5a, 0x19, 0x05, 0x6f, 0x7d, 0xcd, 0x7b,
	0x5f, 0xde, 0xf7, 0x5e, 0x60, 0xaa, 0x45, 0x75, 0x10, 0xd5, 0xdd, 0xbe, 0xd8, 0x9e, 0x44, 0xb5,
	0xdc, 0x57, 0xaa, 0x56, 0x24, 0xb2, 0x88, 0x8d, 0x61, 0xf4, 0x58, 0xca, 0x9a, 0x8b, 0xcf, 0x2f,
	0xa1, 0x6b, 0xf6, 0x0c, 0xb1, 0x85, 0x7a, 0xaf, 0x4a, 0x2d, 0xc8, 0x04, 0x02, 0x99, 0x53, 0x94,
	0xa0, 0xf4, 0x9a, 0x07, 0x32, 0x27, 0x31, 0xa0, 0x23, 0x0d, 0x12, 0x94, 0x22, 0x8e, 0x8e, 0x06,
	0x9d, 0xe8, 0xd0, 0xa2, 0x13, 0x21, 0x80, 0x3f, 0xb6, 0x5a, 0x53, 0x9c, 0xa0, 0x34, 0xe4, 0xcd,
	0x37, 0xdb, 0xc0, 0xe8, 0x49, 0x1d, 0x84, 0x1b, 0xff, 0x9f, 0x71, 0xec, 0x15, 0x62, 0x2b, 0x75,
	0x56, 0x1a, 0x2e, 0xea, 0x70, 0x03, 0x7f, 0xf5, 0x0c, 0xc2, 0x6d, 0x21, 0x0f, 0xa2, 0x51, 0x5f,
	0x71, 0x0b, 0x2e, 0x1a, 0xba, 0x85, 0x31, 0x17, 0x3b, 0xa9, 0x4a, 0x6f, 0xa9, 0x67, 0x2c, 0x7b,
	0x83, 0x89, 0x27, 0x3b, 0x13, 0x0c, 0xc2, 0xac, 0x50, 0x99, 0xa6, 0x28, 0x19, 0xa6, 0xa3, 0x55,
	0xbc, 0x74, 0xa1, 0xde, 0x17, 0x2a, 0xe3, 0xf6, 0xc8, 0x70, 0xde, 0x95, 0xca, 0x35, 0x0d, 0xba,
	0x9c, 0x07, 0xa5, 0x72, 0x6e, 0x8f, 0x58, 0x0e, 0xd8, 0x48, 0xc8, 0x1c, 0x22, 0x5d, 0x57, 0xb2,
	0xdc, 0xb9, 0x50, 0x1c, 0xea, 0xcd, 0xf9, 0x77, 0x59, 0x7c, 0x69, 0xd9, 0xb0, 0xb5, 0x2c, 0x03,
	0x6c, 0x2e, 0xed, 0xdb, 0x71, 0xf5, 0x8d, 0x20, 0x7a, 0x69, 0x0c, 0x92, 0x35, 0x60, 0x53, 0x3e,
	0x99, 0x7a, 0xc7, 0xad, 0x97, 0xb1, 0x98, 0x75, 0x7f, 0xda, 0x3c, 0xd8, 0xc0, 0x88, 0x4c, 0x4d,
	0x67, 0x51, 0xab, 0xef, 0xb3, 0xa8, 0xdd, 0x24, 0x1b, 0x90, 0x0d, 0x44, 0x36, 0x58, 0x72, 0xe3,
	0x19, 0x9d, 0x56, 0x16, 0xf3, 0xbf, 0xbf, 0xbd, 0x34, 0x8b, 0x9a, 0xf7, 0xbb, 0xfe, 0x09, 0x00,
	0x00, 0xff, 0xff, 0x1e, 0x8e, 0x75, 0xbf, 0xd6, 0x02, 0x00, 0x00,
}
