// Code generated by protoc-gen-go. DO NOT EDIT.
// source: player.proto

package player_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{0}
}

func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (m *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(m, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

type InitResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X                    float64  `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Mass                 int32    `protobuf:"varint,4,opt,name=mass,proto3" json:"mass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitResponse) Reset()         { *m = InitResponse{} }
func (m *InitResponse) String() string { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()    {}
func (*InitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{1}
}

func (m *InitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitResponse.Unmarshal(m, b)
}
func (m *InitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitResponse.Marshal(b, m, deterministic)
}
func (m *InitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitResponse.Merge(m, src)
}
func (m *InitResponse) XXX_Size() int {
	return xxx_messageInfo_InitResponse.Size(m)
}
func (m *InitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitResponse proto.InternalMessageInfo

func (m *InitResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InitResponse) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *InitResponse) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *InitResponse) GetMass() int32 {
	if m != nil {
		return m.Mass
	}
	return 0
}

type MoveRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X                    float64  `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveRequest) Reset()         { *m = MoveRequest{} }
func (m *MoveRequest) String() string { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()    {}
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{2}
}

func (m *MoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRequest.Unmarshal(m, b)
}
func (m *MoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRequest.Marshal(b, m, deterministic)
}
func (m *MoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRequest.Merge(m, src)
}
func (m *MoveRequest) XXX_Size() int {
	return xxx_messageInfo_MoveRequest.Size(m)
}
func (m *MoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRequest proto.InternalMessageInfo

func (m *MoveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MoveRequest) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MoveRequest) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type MoveResponse struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Alive                bool     `protobuf:"varint,3,opt,name=alive,proto3" json:"alive,omitempty"`
	Mass                 int32    `protobuf:"varint,4,opt,name=mass,proto3" json:"mass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveResponse) Reset()         { *m = MoveResponse{} }
func (m *MoveResponse) String() string { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()    {}
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{3}
}

func (m *MoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResponse.Unmarshal(m, b)
}
func (m *MoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResponse.Marshal(b, m, deterministic)
}
func (m *MoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResponse.Merge(m, src)
}
func (m *MoveResponse) XXX_Size() int {
	return xxx_messageInfo_MoveResponse.Size(m)
}
func (m *MoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResponse proto.InternalMessageInfo

func (m *MoveResponse) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MoveResponse) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *MoveResponse) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

func (m *MoveResponse) GetMass() int32 {
	if m != nil {
		return m.Mass
	}
	return 0
}

type RegionRequest struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegionRequest) Reset()         { *m = RegionRequest{} }
func (m *RegionRequest) String() string { return proto.CompactTextString(m) }
func (*RegionRequest) ProtoMessage()    {}
func (*RegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{4}
}

func (m *RegionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegionRequest.Unmarshal(m, b)
}
func (m *RegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegionRequest.Marshal(b, m, deterministic)
}
func (m *RegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionRequest.Merge(m, src)
}
func (m *RegionRequest) XXX_Size() int {
	return xxx_messageInfo_RegionRequest.Size(m)
}
func (m *RegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegionRequest proto.InternalMessageInfo

func (m *RegionRequest) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *RegionRequest) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type RegionResponse struct {
	Blobs                []*Blob  `protobuf:"bytes,1,rep,name=blobs,proto3" json:"blobs,omitempty"`
	Foods                []*Food  `protobuf:"bytes,2,rep,name=foods,proto3" json:"foods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegionResponse) Reset()         { *m = RegionResponse{} }
func (m *RegionResponse) String() string { return proto.CompactTextString(m) }
func (*RegionResponse) ProtoMessage()    {}
func (*RegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{5}
}

func (m *RegionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegionResponse.Unmarshal(m, b)
}
func (m *RegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegionResponse.Marshal(b, m, deterministic)
}
func (m *RegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionResponse.Merge(m, src)
}
func (m *RegionResponse) XXX_Size() int {
	return xxx_messageInfo_RegionResponse.Size(m)
}
func (m *RegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegionResponse proto.InternalMessageInfo

func (m *RegionResponse) GetBlobs() []*Blob {
	if m != nil {
		return m.Blobs
	}
	return nil
}

func (m *RegionResponse) GetFoods() []*Food {
	if m != nil {
		return m.Foods
	}
	return nil
}

type MassIncrementRequest struct {
	MassIncrease         int32    `protobuf:"varint,1,opt,name=massIncrease,proto3" json:"massIncrease,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MassIncrementRequest) Reset()         { *m = MassIncrementRequest{} }
func (m *MassIncrementRequest) String() string { return proto.CompactTextString(m) }
func (*MassIncrementRequest) ProtoMessage()    {}
func (*MassIncrementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{6}
}

func (m *MassIncrementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MassIncrementRequest.Unmarshal(m, b)
}
func (m *MassIncrementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MassIncrementRequest.Marshal(b, m, deterministic)
}
func (m *MassIncrementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MassIncrementRequest.Merge(m, src)
}
func (m *MassIncrementRequest) XXX_Size() int {
	return xxx_messageInfo_MassIncrementRequest.Size(m)
}
func (m *MassIncrementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MassIncrementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MassIncrementRequest proto.InternalMessageInfo

func (m *MassIncrementRequest) GetMassIncrease() int32 {
	if m != nil {
		return m.MassIncrease
	}
	return 0
}

type MassIncrementResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MassIncrementResponse) Reset()         { *m = MassIncrementResponse{} }
func (m *MassIncrementResponse) String() string { return proto.CompactTextString(m) }
func (*MassIncrementResponse) ProtoMessage()    {}
func (*MassIncrementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{7}
}

func (m *MassIncrementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MassIncrementResponse.Unmarshal(m, b)
}
func (m *MassIncrementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MassIncrementResponse.Marshal(b, m, deterministic)
}
func (m *MassIncrementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MassIncrementResponse.Merge(m, src)
}
func (m *MassIncrementResponse) XXX_Size() int {
	return xxx_messageInfo_MassIncrementResponse.Size(m)
}
func (m *MassIncrementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MassIncrementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MassIncrementResponse proto.InternalMessageInfo

type Blob struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	X                    float64  `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Alive                bool     `protobuf:"varint,4,opt,name=alive,proto3" json:"alive,omitempty"`
	Mass                 int32    `protobuf:"varint,5,opt,name=mass,proto3" json:"mass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blob) Reset()         { *m = Blob{} }
func (m *Blob) String() string { return proto.CompactTextString(m) }
func (*Blob) ProtoMessage()    {}
func (*Blob) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{8}
}

func (m *Blob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blob.Unmarshal(m, b)
}
func (m *Blob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blob.Marshal(b, m, deterministic)
}
func (m *Blob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blob.Merge(m, src)
}
func (m *Blob) XXX_Size() int {
	return xxx_messageInfo_Blob.Size(m)
}
func (m *Blob) XXX_DiscardUnknown() {
	xxx_messageInfo_Blob.DiscardUnknown(m)
}

var xxx_messageInfo_Blob proto.InternalMessageInfo

func (m *Blob) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Blob) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Blob) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Blob) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

func (m *Blob) GetMass() int32 {
	if m != nil {
		return m.Mass
	}
	return 0
}

type Food struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Food) Reset()         { *m = Food{} }
func (m *Food) String() string { return proto.CompactTextString(m) }
func (*Food) ProtoMessage()    {}
func (*Food) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{9}
}

func (m *Food) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Food.Unmarshal(m, b)
}
func (m *Food) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Food.Marshal(b, m, deterministic)
}
func (m *Food) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Food.Merge(m, src)
}
func (m *Food) XXX_Size() int {
	return xxx_messageInfo_Food.Size(m)
}
func (m *Food) XXX_DiscardUnknown() {
	xxx_messageInfo_Food.DiscardUnknown(m)
}

var xxx_messageInfo_Food proto.InternalMessageInfo

func (m *Food) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Food) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*InitRequest)(nil), "player.InitRequest")
	proto.RegisterType((*InitResponse)(nil), "player.InitResponse")
	proto.RegisterType((*MoveRequest)(nil), "player.MoveRequest")
	proto.RegisterType((*MoveResponse)(nil), "player.MoveResponse")
	proto.RegisterType((*RegionRequest)(nil), "player.RegionRequest")
	proto.RegisterType((*RegionResponse)(nil), "player.RegionResponse")
	proto.RegisterType((*MassIncrementRequest)(nil), "player.MassIncrementRequest")
	proto.RegisterType((*MassIncrementResponse)(nil), "player.MassIncrementResponse")
	proto.RegisterType((*Blob)(nil), "player.Blob")
	proto.RegisterType((*Food)(nil), "player.Food")
}

func init() {
	proto.RegisterFile("player.proto", fileDescriptor_41d803d1b635d5c6)
}

var fileDescriptor_41d803d1b635d5c6 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x41, 0x6b, 0xc2, 0x30,
	0x14, 0x36, 0xb5, 0x2d, 0xdb, 0xb3, 0x7a, 0xc8, 0x74, 0x2b, 0xb2, 0x41, 0xc9, 0xa9, 0x30, 0xf0,
	0xa0, 0x27, 0x77, 0xdc, 0x61, 0xe0, 0x41, 0x19, 0x61, 0x87, 0x1d, 0xd7, 0xae, 0xd9, 0x28, 0xb4,
	0x8d, 0x33, 0x4e, 0xf4, 0xc7, 0x0f, 0x46, 0x92, 0x46, 0x1b, 0x71, 0xc2, 0x6e, 0x7d, 0xef, 0x7d,
	0xdf, 0xcb, 0xf7, 0xbe, 0xf7, 0x0a, 0xc1, 0xb2, 0x48, 0x76, 0x6c, 0x35, 0x5a, 0xae, 0xf8, 0x9a,
	0x63, 0x5f, 0x47, 0xa4, 0x0b, 0x9d, 0x59, 0x95, 0xaf, 0x29, 0xfb, 0xfa, 0x66, 0x62, 0x4d, 0x16,
	0x10, 0xe8, 0x50, 0x2c, 0x79, 0x25, 0x18, 0xee, 0x81, 0x93, 0x67, 0x21, 0x8a, 0x50, 0x7c, 0x49,
	0x9d, 0x3c, 0xc3, 0x01, 0xa0, 0x6d, 0xe8, 0x44, 0x28, 0x46, 0x14, 0x6d, 0x65, 0xb4, 0x0b, 0xdb,
	0x3a, 0xda, 0x61, 0x0c, 0x6e, 0x99, 0x08, 0x11, 0xba, 0x11, 0x8a, 0x3d, 0xaa, 0xbe, 0xc9, 0x14,
	0x3a, 0x73, 0xbe, 0x61, 0x75, 0xfb, 0xff, 0xb4, 0x23, 0x2f, 0x10, 0x68, 0x6a, 0x2d, 0x45, 0x61,
	0x91, 0x85, 0x75, 0xcc, 0xd3, 0x7d, 0xf0, 0x92, 0x22, 0xdf, 0x30, 0xc5, 0xbe, 0xa0, 0x3a, 0x38,
	0x29, 0xe8, 0x1e, 0xba, 0x94, 0x7d, 0xe6, 0xbc, 0x32, 0x92, 0xce, 0xb4, 0x25, 0xaf, 0xd0, 0x33,
	0xe0, 0x5a, 0x04, 0x01, 0x2f, 0x2d, 0x78, 0x2a, 0x42, 0x14, 0xb5, 0xe3, 0xce, 0x38, 0x18, 0xd5,
	0xa6, 0x3e, 0x16, 0x3c, 0xa5, 0xba, 0x24, 0x31, 0x1f, 0x9c, 0x67, 0x22, 0x74, 0x6c, 0xcc, 0x13,
	0xe7, 0x19, 0xd5, 0x25, 0xf2, 0x00, 0xfd, 0x79, 0x22, 0xc4, 0xac, 0x7a, 0x5f, 0xb1, 0x92, 0x55,
	0xc6, 0x7f, 0x4c, 0x20, 0x28, 0x4d, 0x3e, 0x11, 0x4c, 0x09, 0xf3, 0xa8, 0x95, 0x23, 0x37, 0x30,
	0x38, 0xe2, 0x6a, 0x71, 0xe4, 0x0d, 0x5c, 0xa9, 0x43, 0xce, 0x5d, 0x25, 0x25, 0xab, 0x7d, 0x56,
	0xdf, 0x67, 0x17, 0xb7, 0x77, 0xcf, 0x3d, 0xe5, 0x9e, 0xd7, 0x70, 0x8f, 0x80, 0x2b, 0xa7, 0x38,
	0x67, 0xda, 0xf8, 0x07, 0x81, 0xff, 0xac, 0x26, 0xc6, 0x13, 0x70, 0xe5, 0x35, 0xe1, 0x2b, 0x63,
	0x41, 0xe3, 0xd4, 0x86, 0x7d, 0x3b, 0x59, 0xcf, 0xd0, 0x92, 0x24, 0xb9, 0xf7, 0x03, 0xa9, 0x71,
	0x40, 0x07, 0x52, 0xf3, 0x34, 0x48, 0x0b, 0x4f, 0xc1, 0xd7, 0x9b, 0xc2, 0x03, 0x83, 0xb0, 0xd6,
	0x3c, 0xbc, 0x3e, 0x4e, 0xef, 0xa9, 0x0b, 0xe8, 0x5a, 0x76, 0xe2, 0xdb, 0xfd, 0x1b, 0x27, 0x36,
	0x34, 0xbc, 0xfb, 0xa3, 0x6a, 0xfa, 0xa5, 0xbe, 0xfa, 0xc1, 0x26, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xb6, 0xc7, 0xee, 0x09, 0x70, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PlayerClient is the client API for Player service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayerClient interface {
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error)
	Region(ctx context.Context, in *RegionRequest, opts ...grpc.CallOption) (*RegionResponse, error)
	MassIncrement(ctx context.Context, in *MassIncrementRequest, opts ...grpc.CallOption) (*MassIncrementResponse, error)
}

type playerClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerClient(cc grpc.ClientConnInterface) PlayerClient {
	return &playerClient{cc}
}

func (c *playerClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, "/player.Player/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, "/player.Player/Move", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) Region(ctx context.Context, in *RegionRequest, opts ...grpc.CallOption) (*RegionResponse, error) {
	out := new(RegionResponse)
	err := c.cc.Invoke(ctx, "/player.Player/Region", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) MassIncrement(ctx context.Context, in *MassIncrementRequest, opts ...grpc.CallOption) (*MassIncrementResponse, error) {
	out := new(MassIncrementResponse)
	err := c.cc.Invoke(ctx, "/player.Player/MassIncrement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerServer is the server API for Player service.
type PlayerServer interface {
	Init(context.Context, *InitRequest) (*InitResponse, error)
	Move(context.Context, *MoveRequest) (*MoveResponse, error)
	Region(context.Context, *RegionRequest) (*RegionResponse, error)
	MassIncrement(context.Context, *MassIncrementRequest) (*MassIncrementResponse, error)
}

// UnimplementedPlayerServer can be embedded to have forward compatible implementations.
type UnimplementedPlayerServer struct {
}

func (*UnimplementedPlayerServer) Init(ctx context.Context, req *InitRequest) (*InitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (*UnimplementedPlayerServer) Move(ctx context.Context, req *MoveRequest) (*MoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Move not implemented")
}
func (*UnimplementedPlayerServer) Region(ctx context.Context, req *RegionRequest) (*RegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Region not implemented")
}
func (*UnimplementedPlayerServer) MassIncrement(ctx context.Context, req *MassIncrementRequest) (*MassIncrementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MassIncrement not implemented")
}

func RegisterPlayerServer(s *grpc.Server, srv PlayerServer) {
	s.RegisterService(&_Player_serviceDesc, srv)
}

func _Player_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player.Player/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player.Player/Move",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).Move(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_Region_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).Region(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player.Player/Region",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).Region(ctx, req.(*RegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_MassIncrement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MassIncrementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).MassIncrement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player.Player/MassIncrement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).MassIncrement(ctx, req.(*MassIncrementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Player_serviceDesc = grpc.ServiceDesc{
	ServiceName: "player.Player",
	HandlerType: (*PlayerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Player_Init_Handler,
		},
		{
			MethodName: "Move",
			Handler:    _Player_Move_Handler,
		},
		{
			MethodName: "Region",
			Handler:    _Player_Region_Handler,
		},
		{
			MethodName: "MassIncrement",
			Handler:    _Player_MassIncrement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "player.proto",
}
