# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from entryserver import entry_pb2 as entryserver_dot_entry__pb2


class EntryServerStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Join = channel.unary_unary(
                '/entryserver.EntryServer/Join',
                request_serializer=entryserver_dot_entry__pb2.JoinRequest.SerializeToString,
                response_deserializer=entryserver_dot_entry__pb2.JoinReply.FromString,
                )
        self.CanStart = channel.unary_unary(
                '/entryserver.EntryServer/CanStart',
                request_serializer=entryserver_dot_entry__pb2.CanStartRequest.SerializeToString,
                response_deserializer=entryserver_dot_entry__pb2.CanStartReply.FromString,
                )


class EntryServerServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Join(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CanStart(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EntryServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Join': grpc.unary_unary_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=entryserver_dot_entry__pb2.JoinRequest.FromString,
                    response_serializer=entryserver_dot_entry__pb2.JoinReply.SerializeToString,
            ),
            'CanStart': grpc.unary_unary_rpc_method_handler(
                    servicer.CanStart,
                    request_deserializer=entryserver_dot_entry__pb2.CanStartRequest.FromString,
                    response_serializer=entryserver_dot_entry__pb2.CanStartReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'entryserver.EntryServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EntryServer(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/entryserver.EntryServer/Join',
            entryserver_dot_entry__pb2.JoinRequest.SerializeToString,
            entryserver_dot_entry__pb2.JoinReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CanStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/entryserver.EntryServer/CanStart',
            entryserver_dot_entry__pb2.CanStartRequest.SerializeToString,
            entryserver_dot_entry__pb2.CanStartReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
