# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entryserver/entry.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='entryserver/entry.proto',
  package='entryserver',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x17\x65ntryserver/entry.proto\x12\x0b\x65ntryserver\"\x11\n\x0f\x43\x61nStartRequest\"!\n\rCanStartReply\x12\x10\n\x08\x63\x61nStart\x18\x01 \x01(\x08\"\x19\n\x0bJoinRequest\x12\n\n\x02ip\x18\x01 \x01(\t\":\n\tJoinReply\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x11\n\tmapLength\x18\x03 \x01(\x05\x32\x91\x01\n\x0b\x45ntryServer\x12:\n\x04Join\x12\x18.entryserver.JoinRequest\x1a\x16.entryserver.JoinReply\"\x00\x12\x46\n\x08\x43\x61nStart\x12\x1c.entryserver.CanStartRequest\x1a\x1a.entryserver.CanStartReply\"\x00\x62\x06proto3'
)




_CANSTARTREQUEST = _descriptor.Descriptor(
  name='CanStartRequest',
  full_name='entryserver.CanStartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=57,
)


_CANSTARTREPLY = _descriptor.Descriptor(
  name='CanStartReply',
  full_name='entryserver.CanStartReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='canStart', full_name='entryserver.CanStartReply.canStart', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=92,
)


_JOINREQUEST = _descriptor.Descriptor(
  name='JoinRequest',
  full_name='entryserver.JoinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='entryserver.JoinRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=119,
)


_JOINREPLY = _descriptor.Descriptor(
  name='JoinReply',
  full_name='entryserver.JoinReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='entryserver.JoinReply.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='entryserver.JoinReply.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mapLength', full_name='entryserver.JoinReply.mapLength', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=179,
)

DESCRIPTOR.message_types_by_name['CanStartRequest'] = _CANSTARTREQUEST
DESCRIPTOR.message_types_by_name['CanStartReply'] = _CANSTARTREPLY
DESCRIPTOR.message_types_by_name['JoinRequest'] = _JOINREQUEST
DESCRIPTOR.message_types_by_name['JoinReply'] = _JOINREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CanStartRequest = _reflection.GeneratedProtocolMessageType('CanStartRequest', (_message.Message,), {
  'DESCRIPTOR' : _CANSTARTREQUEST,
  '__module__' : 'entryserver.entry_pb2'
  # @@protoc_insertion_point(class_scope:entryserver.CanStartRequest)
  })
_sym_db.RegisterMessage(CanStartRequest)

CanStartReply = _reflection.GeneratedProtocolMessageType('CanStartReply', (_message.Message,), {
  'DESCRIPTOR' : _CANSTARTREPLY,
  '__module__' : 'entryserver.entry_pb2'
  # @@protoc_insertion_point(class_scope:entryserver.CanStartReply)
  })
_sym_db.RegisterMessage(CanStartReply)

JoinRequest = _reflection.GeneratedProtocolMessageType('JoinRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOINREQUEST,
  '__module__' : 'entryserver.entry_pb2'
  # @@protoc_insertion_point(class_scope:entryserver.JoinRequest)
  })
_sym_db.RegisterMessage(JoinRequest)

JoinReply = _reflection.GeneratedProtocolMessageType('JoinReply', (_message.Message,), {
  'DESCRIPTOR' : _JOINREPLY,
  '__module__' : 'entryserver.entry_pb2'
  # @@protoc_insertion_point(class_scope:entryserver.JoinReply)
  })
_sym_db.RegisterMessage(JoinReply)



_ENTRYSERVER = _descriptor.ServiceDescriptor(
  name='EntryServer',
  full_name='entryserver.EntryServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=182,
  serialized_end=327,
  methods=[
  _descriptor.MethodDescriptor(
    name='Join',
    full_name='entryserver.EntryServer.Join',
    index=0,
    containing_service=None,
    input_type=_JOINREQUEST,
    output_type=_JOINREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CanStart',
    full_name='entryserver.EntryServer.CanStart',
    index=1,
    containing_service=None,
    input_type=_CANSTARTREQUEST,
    output_type=_CANSTARTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ENTRYSERVER)

DESCRIPTOR.services_by_name['EntryServer'] = _ENTRYSERVER

# @@protoc_insertion_point(module_scope)
