# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import player_pb2 as player__pb2


class PlayerStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/player.Player/Init',
                request_serializer=player__pb2.InitRequest.SerializeToString,
                response_deserializer=player__pb2.InitResponse.FromString,
                )
        self.Move = channel.unary_unary(
                '/player.Player/Move',
                request_serializer=player__pb2.MoveRequest.SerializeToString,
                response_deserializer=player__pb2.MoveResponse.FromString,
                )
        self.Region = channel.unary_unary(
                '/player.Player/Region',
                request_serializer=player__pb2.RegionRequest.SerializeToString,
                response_deserializer=player__pb2.RegionResponse.FromString,
                )
        self.MassIncrement = channel.unary_unary(
                '/player.Player/MassIncrement',
                request_serializer=player__pb2.MassIncrementRequest.SerializeToString,
                response_deserializer=player__pb2.MassIncrementResponse.FromString,
                )


class PlayerServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Region(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MassIncrement(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=player__pb2.InitRequest.FromString,
                    response_serializer=player__pb2.InitResponse.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=player__pb2.MoveRequest.FromString,
                    response_serializer=player__pb2.MoveResponse.SerializeToString,
            ),
            'Region': grpc.unary_unary_rpc_method_handler(
                    servicer.Region,
                    request_deserializer=player__pb2.RegionRequest.FromString,
                    response_serializer=player__pb2.RegionResponse.SerializeToString,
            ),
            'MassIncrement': grpc.unary_unary_rpc_method_handler(
                    servicer.MassIncrement,
                    request_deserializer=player__pb2.MassIncrementRequest.FromString,
                    response_serializer=player__pb2.MassIncrementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'player.Player', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Player(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/player.Player/Init',
            player__pb2.InitRequest.SerializeToString,
            player__pb2.InitResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/player.Player/Move',
            player__pb2.MoveRequest.SerializeToString,
            player__pb2.MoveResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Region(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/player.Player/Region',
            player__pb2.RegionRequest.SerializeToString,
            player__pb2.RegionResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MassIncrement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/player.Player/MassIncrement',
            player__pb2.MassIncrementRequest.SerializeToString,
            player__pb2.MassIncrementResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
