# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='player.proto',
  package='player',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cplayer.proto\x12\x06player\"\r\n\x0bInitRequest\">\n\x0cInitResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\x0c\n\x04mass\x18\x04 \x01(\x05\"/\n\x0bMoveRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\"A\n\x0cMoveResponse\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\r\n\x05\x61live\x18\x03 \x01(\x08\x12\x0c\n\x04mass\x18\x04 \x01(\x05\"%\n\rRegionRequest\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"J\n\x0eRegionResponse\x12\x1b\n\x05\x62lobs\x18\x01 \x03(\x0b\x32\x0c.player.Blob\x12\x1b\n\x05\x66oods\x18\x02 \x03(\x0b\x32\x0c.player.Food\",\n\x14MassIncrementRequest\x12\x14\n\x0cmassIncrease\x18\x01 \x01(\x05\"\x17\n\x15MassIncrementResponse\"G\n\x04\x42lob\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\r\n\x05\x61live\x18\x04 \x01(\x08\x12\x0c\n\x04mass\x18\x05 \x01(\x05\"\x1c\n\x04\x46ood\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x32\xfd\x01\n\x06Player\x12\x33\n\x04Init\x12\x13.player.InitRequest\x1a\x14.player.InitResponse\"\x00\x12\x33\n\x04Move\x12\x13.player.MoveRequest\x1a\x14.player.MoveResponse\"\x00\x12\x39\n\x06Region\x12\x15.player.RegionRequest\x1a\x16.player.RegionResponse\"\x00\x12N\n\rMassIncrement\x12\x1c.player.MassIncrementRequest\x1a\x1d.player.MassIncrementResponse\"\x00\x62\x06proto3'
)




_INITREQUEST = _descriptor.Descriptor(
  name='InitRequest',
  full_name='player.InitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=37,
)


_INITRESPONSE = _descriptor.Descriptor(
  name='InitResponse',
  full_name='player.InitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='player.InitResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='player.InitResponse.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='player.InitResponse.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mass', full_name='player.InitResponse.mass', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=101,
)


_MOVEREQUEST = _descriptor.Descriptor(
  name='MoveRequest',
  full_name='player.MoveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='player.MoveRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='player.MoveRequest.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='player.MoveRequest.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=150,
)


_MOVERESPONSE = _descriptor.Descriptor(
  name='MoveResponse',
  full_name='player.MoveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='player.MoveResponse.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='player.MoveResponse.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alive', full_name='player.MoveResponse.alive', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mass', full_name='player.MoveResponse.mass', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=217,
)


_REGIONREQUEST = _descriptor.Descriptor(
  name='RegionRequest',
  full_name='player.RegionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='player.RegionRequest.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='player.RegionRequest.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=256,
)


_REGIONRESPONSE = _descriptor.Descriptor(
  name='RegionResponse',
  full_name='player.RegionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blobs', full_name='player.RegionResponse.blobs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='foods', full_name='player.RegionResponse.foods', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=332,
)


_MASSINCREMENTREQUEST = _descriptor.Descriptor(
  name='MassIncrementRequest',
  full_name='player.MassIncrementRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='massIncrease', full_name='player.MassIncrementRequest.massIncrease', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=378,
)


_MASSINCREMENTRESPONSE = _descriptor.Descriptor(
  name='MassIncrementResponse',
  full_name='player.MassIncrementResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=403,
)


_BLOB = _descriptor.Descriptor(
  name='Blob',
  full_name='player.Blob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='player.Blob.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='player.Blob.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='player.Blob.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alive', full_name='player.Blob.alive', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mass', full_name='player.Blob.mass', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=476,
)


_FOOD = _descriptor.Descriptor(
  name='Food',
  full_name='player.Food',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='player.Food.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='player.Food.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=506,
)

_REGIONRESPONSE.fields_by_name['blobs'].message_type = _BLOB
_REGIONRESPONSE.fields_by_name['foods'].message_type = _FOOD
DESCRIPTOR.message_types_by_name['InitRequest'] = _INITREQUEST
DESCRIPTOR.message_types_by_name['InitResponse'] = _INITRESPONSE
DESCRIPTOR.message_types_by_name['MoveRequest'] = _MOVEREQUEST
DESCRIPTOR.message_types_by_name['MoveResponse'] = _MOVERESPONSE
DESCRIPTOR.message_types_by_name['RegionRequest'] = _REGIONREQUEST
DESCRIPTOR.message_types_by_name['RegionResponse'] = _REGIONRESPONSE
DESCRIPTOR.message_types_by_name['MassIncrementRequest'] = _MASSINCREMENTREQUEST
DESCRIPTOR.message_types_by_name['MassIncrementResponse'] = _MASSINCREMENTRESPONSE
DESCRIPTOR.message_types_by_name['Blob'] = _BLOB
DESCRIPTOR.message_types_by_name['Food'] = _FOOD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitRequest = _reflection.GeneratedProtocolMessageType('InitRequest', (_message.Message,), {
  'DESCRIPTOR' : _INITREQUEST,
  '__module__' : 'player_pb2'
  # @@protoc_insertion_point(class_scope:player.InitRequest)
  })
_sym_db.RegisterMessage(InitRequest)

InitResponse = _reflection.GeneratedProtocolMessageType('InitResponse', (_message.Message,), {
  'DESCRIPTOR' : _INITRESPONSE,
  '__module__' : 'player_pb2'
  # @@protoc_insertion_point(class_scope:player.InitResponse)
  })
_sym_db.RegisterMessage(InitResponse)

MoveRequest = _reflection.GeneratedProtocolMessageType('MoveRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOVEREQUEST,
  '__module__' : 'player_pb2'
  # @@protoc_insertion_point(class_scope:player.MoveRequest)
  })
_sym_db.RegisterMessage(MoveRequest)

MoveResponse = _reflection.GeneratedProtocolMessageType('MoveResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOVERESPONSE,
  '__module__' : 'player_pb2'
  # @@protoc_insertion_point(class_scope:player.MoveResponse)
  })
_sym_db.RegisterMessage(MoveResponse)

RegionRequest = _reflection.GeneratedProtocolMessageType('RegionRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGIONREQUEST,
  '__module__' : 'player_pb2'
  # @@protoc_insertion_point(class_scope:player.RegionRequest)
  })
_sym_db.RegisterMessage(RegionRequest)

RegionResponse = _reflection.GeneratedProtocolMessageType('RegionResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGIONRESPONSE,
  '__module__' : 'player_pb2'
  # @@protoc_insertion_point(class_scope:player.RegionResponse)
  })
_sym_db.RegisterMessage(RegionResponse)

MassIncrementRequest = _reflection.GeneratedProtocolMessageType('MassIncrementRequest', (_message.Message,), {
  'DESCRIPTOR' : _MASSINCREMENTREQUEST,
  '__module__' : 'player_pb2'
  # @@protoc_insertion_point(class_scope:player.MassIncrementRequest)
  })
_sym_db.RegisterMessage(MassIncrementRequest)

MassIncrementResponse = _reflection.GeneratedProtocolMessageType('MassIncrementResponse', (_message.Message,), {
  'DESCRIPTOR' : _MASSINCREMENTRESPONSE,
  '__module__' : 'player_pb2'
  # @@protoc_insertion_point(class_scope:player.MassIncrementResponse)
  })
_sym_db.RegisterMessage(MassIncrementResponse)

Blob = _reflection.GeneratedProtocolMessageType('Blob', (_message.Message,), {
  'DESCRIPTOR' : _BLOB,
  '__module__' : 'player_pb2'
  # @@protoc_insertion_point(class_scope:player.Blob)
  })
_sym_db.RegisterMessage(Blob)

Food = _reflection.GeneratedProtocolMessageType('Food', (_message.Message,), {
  'DESCRIPTOR' : _FOOD,
  '__module__' : 'player_pb2'
  # @@protoc_insertion_point(class_scope:player.Food)
  })
_sym_db.RegisterMessage(Food)



_PLAYER = _descriptor.ServiceDescriptor(
  name='Player',
  full_name='player.Player',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=509,
  serialized_end=762,
  methods=[
  _descriptor.MethodDescriptor(
    name='Init',
    full_name='player.Player.Init',
    index=0,
    containing_service=None,
    input_type=_INITREQUEST,
    output_type=_INITRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Move',
    full_name='player.Player.Move',
    index=1,
    containing_service=None,
    input_type=_MOVEREQUEST,
    output_type=_MOVERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Region',
    full_name='player.Player.Region',
    index=2,
    containing_service=None,
    input_type=_REGIONREQUEST,
    output_type=_REGIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MassIncrement',
    full_name='player.Player.MassIncrement',
    index=3,
    containing_service=None,
    input_type=_MASSINCREMENTREQUEST,
    output_type=_MASSINCREMENTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLAYER)

DESCRIPTOR.services_by_name['Player'] = _PLAYER

# @@protoc_insertion_point(module_scope)
