// Code generated by protoc-gen-go. DO NOT EDIT.
// source: region.proto

package region

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eef30384a8831dd, []int{0}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eef30384a8831dd, []int{1}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type AddRegionRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Foods                []*Food  `protobuf:"bytes,2,rep,name=foods,proto3" json:"foods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRegionRequest) Reset()         { *m = AddRegionRequest{} }
func (m *AddRegionRequest) String() string { return proto.CompactTextString(m) }
func (*AddRegionRequest) ProtoMessage()    {}
func (*AddRegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eef30384a8831dd, []int{2}
}

func (m *AddRegionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRegionRequest.Unmarshal(m, b)
}
func (m *AddRegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRegionRequest.Marshal(b, m, deterministic)
}
func (m *AddRegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRegionRequest.Merge(m, src)
}
func (m *AddRegionRequest) XXX_Size() int {
	return xxx_messageInfo_AddRegionRequest.Size(m)
}
func (m *AddRegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRegionRequest proto.InternalMessageInfo

func (m *AddRegionRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddRegionRequest) GetFoods() []*Food {
	if m != nil {
		return m.Foods
	}
	return nil
}

type IdRegionRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRegionRequest) Reset()         { *m = IdRegionRequest{} }
func (m *IdRegionRequest) String() string { return proto.CompactTextString(m) }
func (*IdRegionRequest) ProtoMessage()    {}
func (*IdRegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eef30384a8831dd, []int{3}
}

func (m *IdRegionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRegionRequest.Unmarshal(m, b)
}
func (m *IdRegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRegionRequest.Marshal(b, m, deterministic)
}
func (m *IdRegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRegionRequest.Merge(m, src)
}
func (m *IdRegionRequest) XXX_Size() int {
	return xxx_messageInfo_IdRegionRequest.Size(m)
}
func (m *IdRegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRegionRequest proto.InternalMessageInfo

func (m *IdRegionRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetRegionResponse struct {
	Blobs                []*Blob  `protobuf:"bytes,1,rep,name=blobs,proto3" json:"blobs,omitempty"`
	Foods                []*Food  `protobuf:"bytes,2,rep,name=foods,proto3" json:"foods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRegionResponse) Reset()         { *m = GetRegionResponse{} }
func (m *GetRegionResponse) String() string { return proto.CompactTextString(m) }
func (*GetRegionResponse) ProtoMessage()    {}
func (*GetRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eef30384a8831dd, []int{4}
}

func (m *GetRegionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRegionResponse.Unmarshal(m, b)
}
func (m *GetRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRegionResponse.Marshal(b, m, deterministic)
}
func (m *GetRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRegionResponse.Merge(m, src)
}
func (m *GetRegionResponse) XXX_Size() int {
	return xxx_messageInfo_GetRegionResponse.Size(m)
}
func (m *GetRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRegionResponse proto.InternalMessageInfo

func (m *GetRegionResponse) GetBlobs() []*Blob {
	if m != nil {
		return m.Blobs
	}
	return nil
}

func (m *GetRegionResponse) GetFoods() []*Food {
	if m != nil {
		return m.Foods
	}
	return nil
}

type UpdateRegionRequest struct {
	Blob                 *Blob    `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
	Id                   uint32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRegionRequest) Reset()         { *m = UpdateRegionRequest{} }
func (m *UpdateRegionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRegionRequest) ProtoMessage()    {}
func (*UpdateRegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eef30384a8831dd, []int{5}
}

func (m *UpdateRegionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRegionRequest.Unmarshal(m, b)
}
func (m *UpdateRegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRegionRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRegionRequest.Merge(m, src)
}
func (m *UpdateRegionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRegionRequest.Size(m)
}
func (m *UpdateRegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRegionRequest proto.InternalMessageInfo

func (m *UpdateRegionRequest) GetBlob() *Blob {
	if m != nil {
		return m.Blob
	}
	return nil
}

func (m *UpdateRegionRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateRegionResponse struct {
	DeltaMass            int32    `protobuf:"varint,1,opt,name=deltaMass,proto3" json:"deltaMass,omitempty"`
	Alive                bool     `protobuf:"varint,2,opt,name=alive,proto3" json:"alive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRegionResponse) Reset()         { *m = UpdateRegionResponse{} }
func (m *UpdateRegionResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRegionResponse) ProtoMessage()    {}
func (*UpdateRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eef30384a8831dd, []int{6}
}

func (m *UpdateRegionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRegionResponse.Unmarshal(m, b)
}
func (m *UpdateRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRegionResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRegionResponse.Merge(m, src)
}
func (m *UpdateRegionResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRegionResponse.Size(m)
}
func (m *UpdateRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRegionResponse proto.InternalMessageInfo

func (m *UpdateRegionResponse) GetDeltaMass() int32 {
	if m != nil {
		return m.DeltaMass
	}
	return 0
}

func (m *UpdateRegionResponse) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

type FoodRequest struct {
	Foods                []*Food  `protobuf:"bytes,1,rep,name=foods,proto3" json:"foods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodRequest) Reset()         { *m = FoodRequest{} }
func (m *FoodRequest) String() string { return proto.CompactTextString(m) }
func (*FoodRequest) ProtoMessage()    {}
func (*FoodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eef30384a8831dd, []int{7}
}

func (m *FoodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodRequest.Unmarshal(m, b)
}
func (m *FoodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodRequest.Marshal(b, m, deterministic)
}
func (m *FoodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodRequest.Merge(m, src)
}
func (m *FoodRequest) XXX_Size() int {
	return xxx_messageInfo_FoodRequest.Size(m)
}
func (m *FoodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FoodRequest proto.InternalMessageInfo

func (m *FoodRequest) GetFoods() []*Food {
	if m != nil {
		return m.Foods
	}
	return nil
}

type Blob struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	X                    float64  `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Alive                bool     `protobuf:"varint,4,opt,name=alive,proto3" json:"alive,omitempty"`
	Mass                 int32    `protobuf:"varint,5,opt,name=mass,proto3" json:"mass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blob) Reset()         { *m = Blob{} }
func (m *Blob) String() string { return proto.CompactTextString(m) }
func (*Blob) ProtoMessage()    {}
func (*Blob) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eef30384a8831dd, []int{8}
}

func (m *Blob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blob.Unmarshal(m, b)
}
func (m *Blob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blob.Marshal(b, m, deterministic)
}
func (m *Blob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blob.Merge(m, src)
}
func (m *Blob) XXX_Size() int {
	return xxx_messageInfo_Blob.Size(m)
}
func (m *Blob) XXX_DiscardUnknown() {
	xxx_messageInfo_Blob.DiscardUnknown(m)
}

var xxx_messageInfo_Blob proto.InternalMessageInfo

func (m *Blob) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Blob) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Blob) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Blob) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

func (m *Blob) GetMass() int32 {
	if m != nil {
		return m.Mass
	}
	return 0
}

type Food struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Food) Reset()         { *m = Food{} }
func (m *Food) String() string { return proto.CompactTextString(m) }
func (*Food) ProtoMessage()    {}
func (*Food) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eef30384a8831dd, []int{9}
}

func (m *Food) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Food.Unmarshal(m, b)
}
func (m *Food) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Food.Marshal(b, m, deterministic)
}
func (m *Food) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Food.Merge(m, src)
}
func (m *Food) XXX_Size() int {
	return xxx_messageInfo_Food.Size(m)
}
func (m *Food) XXX_DiscardUnknown() {
	xxx_messageInfo_Food.DiscardUnknown(m)
}

var xxx_messageInfo_Food proto.InternalMessageInfo

func (m *Food) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Food) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "region.EmptyRequest")
	proto.RegisterType((*EmptyResponse)(nil), "region.EmptyResponse")
	proto.RegisterType((*AddRegionRequest)(nil), "region.AddRegionRequest")
	proto.RegisterType((*IdRegionRequest)(nil), "region.IdRegionRequest")
	proto.RegisterType((*GetRegionResponse)(nil), "region.GetRegionResponse")
	proto.RegisterType((*UpdateRegionRequest)(nil), "region.UpdateRegionRequest")
	proto.RegisterType((*UpdateRegionResponse)(nil), "region.UpdateRegionResponse")
	proto.RegisterType((*FoodRequest)(nil), "region.FoodRequest")
	proto.RegisterType((*Blob)(nil), "region.Blob")
	proto.RegisterType((*Food)(nil), "region.Food")
}

func init() {
	proto.RegisterFile("region.proto", fileDescriptor_6eef30384a8831dd)
}

var fileDescriptor_6eef30384a8831dd = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0xaa, 0xd3, 0x40,
	0x14, 0x87, 0xef, 0xa4, 0x49, 0xb9, 0x39, 0xcd, 0xbd, 0x57, 0xa7, 0x15, 0x63, 0xed, 0xa2, 0xce,
	0xaa, 0xab, 0x82, 0x15, 0x41, 0x10, 0xc4, 0x2a, 0xb6, 0xa8, 0x08, 0x32, 0xe0, 0xca, 0x8d, 0x09,
	0x33, 0x96, 0x40, 0x92, 0x89, 0x9d, 0x58, 0x9a, 0x37, 0xf4, 0xb1, 0x64, 0xfe, 0x24, 0x6d, 0x62,
	0x6b, 0xc5, 0x5d, 0x4e, 0xce, 0x99, 0xef, 0x7c, 0xd3, 0xfe, 0x08, 0x04, 0x5b, 0xbe, 0x49, 0x44,
	0x3e, 0x2f, 0xb6, 0xa2, 0x14, 0xb8, 0x6f, 0x2a, 0x72, 0x0b, 0xc1, 0xbb, 0xac, 0x28, 0x2b, 0xca,
	0x7f, 0xfc, 0xe4, 0xb2, 0x24, 0x77, 0x70, 0x63, 0x6b, 0x59, 0x88, 0x5c, 0x72, 0xb2, 0x82, 0x7b,
	0x4b, 0xc6, 0xa8, 0x9e, 0xb6, 0x43, 0xf8, 0x16, 0x9c, 0x84, 0x85, 0x68, 0x8a, 0x66, 0x37, 0xd4,
	0x49, 0x18, 0x26, 0xe0, 0x7d, 0x17, 0x82, 0xc9, 0xd0, 0x99, 0xf6, 0x66, 0x83, 0x45, 0x30, 0xb7,
	0xab, 0x56, 0x42, 0x30, 0x6a, 0x5a, 0xe4, 0x09, 0xdc, 0xbd, 0xff, 0x3b, 0x86, 0x7c, 0x85, 0xfb,
	0x6b, 0x5e, 0xd6, 0x33, 0x66, 0xbf, 0x62, 0xc7, 0xa9, 0x88, 0x65, 0x88, 0xda, 0xec, 0x37, 0xa9,
	0x88, 0xa9, 0x69, 0xfd, 0xd3, 0xfe, 0x35, 0x0c, 0xbf, 0x14, 0x2c, 0x2a, 0x79, 0xdb, 0x61, 0x0a,
	0xae, 0x62, 0x68, 0x8b, 0x2e, 0x5d, 0x77, 0xac, 0xa5, 0xd3, 0x58, 0x7e, 0x80, 0x51, 0x1b, 0x64,
	0x45, 0x27, 0xe0, 0x33, 0x9e, 0x96, 0xd1, 0xa7, 0x48, 0x4a, 0x8d, 0xf3, 0xe8, 0xe1, 0x05, 0x1e,
	0x81, 0x17, 0xa5, 0xc9, 0x8e, 0x6b, 0xd0, 0x35, 0x35, 0x05, 0x79, 0x0a, 0x03, 0xed, 0x68, 0x65,
	0x9a, 0x7b, 0xa0, 0xf3, 0xf7, 0xf8, 0x06, 0xae, 0x92, 0xc3, 0x18, 0xdc, 0x3c, 0xca, 0xb8, 0xde,
	0xe4, 0x53, 0xfd, 0x8c, 0x03, 0x40, 0x7b, 0xbd, 0x00, 0x51, 0xb4, 0x57, 0x55, 0x15, 0xf6, 0x4c,
	0x55, 0x1d, 0x04, 0xdc, 0x23, 0x01, 0x45, 0xc9, 0x94, 0xaf, 0xa7, 0x7d, 0xf5, 0x33, 0x21, 0xe0,
	0xaa, 0x85, 0x86, 0x86, 0x5a, 0x34, 0xcb, 0xae, 0x16, 0xbf, 0x7a, 0xd0, 0x37, 0xf7, 0xc7, 0xcf,
	0xc1, 0xfd, 0x9c, 0xe4, 0x1b, 0x3c, 0xaa, 0x6d, 0x8f, 0xf3, 0x34, 0x7e, 0xd0, 0x79, 0x6b, 0x53,
	0x75, 0x85, 0x5f, 0x81, 0xdf, 0xe4, 0x0a, 0x87, 0xf5, 0x54, 0x37, 0x6a, 0xe7, 0xcf, 0x2f, 0xc1,
	0x6f, 0xc2, 0x82, 0x1f, 0xd6, 0x53, 0x9d, 0x88, 0x8d, 0x1f, 0xd5, 0x8d, 0x3f, 0x82, 0x45, 0xae,
	0xf0, 0x6b, 0x08, 0x28, 0xcf, 0xc4, 0x8e, 0x5f, 0xa2, 0x9c, 0x95, 0xf8, 0x08, 0xc1, 0xdb, 0x34,
	0xe1, 0x79, 0x69, 0x12, 0x81, 0x1f, 0xd7, 0x83, 0x27, 0xa2, 0x36, 0x9e, 0x9c, 0x6e, 0x36, 0xb0,
	0x17, 0x70, 0xbd, 0x64, 0x4c, 0xfd, 0xf4, 0x12, 0x0f, 0x5b, 0x7f, 0xfd, 0x25, 0x8d, 0x97, 0x30,
	0x30, 0x17, 0xf9, 0x8f, 0xc3, 0x71, 0x5f, 0x7f, 0x10, 0x9e, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0x05, 0x34, 0xde, 0x73, 0x20, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RegionClient is the client API for Region service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegionClient interface {
	Ping(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	AddRegion(ctx context.Context, in *AddRegionRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	GetRegion(ctx context.Context, in *IdRegionRequest, opts ...grpc.CallOption) (*GetRegionResponse, error)
	RemoveRegion(ctx context.Context, in *IdRegionRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	ClientUpdate(ctx context.Context, in *UpdateRegionRequest, opts ...grpc.CallOption) (*UpdateRegionResponse, error)
	AddFoods(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	RemoveFoods(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type regionClient struct {
	cc grpc.ClientConnInterface
}

func NewRegionClient(cc grpc.ClientConnInterface) RegionClient {
	return &regionClient{cc}
}

func (c *regionClient) Ping(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/region.Region/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionClient) AddRegion(ctx context.Context, in *AddRegionRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/region.Region/AddRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionClient) GetRegion(ctx context.Context, in *IdRegionRequest, opts ...grpc.CallOption) (*GetRegionResponse, error) {
	out := new(GetRegionResponse)
	err := c.cc.Invoke(ctx, "/region.Region/GetRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionClient) RemoveRegion(ctx context.Context, in *IdRegionRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/region.Region/RemoveRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionClient) ClientUpdate(ctx context.Context, in *UpdateRegionRequest, opts ...grpc.CallOption) (*UpdateRegionResponse, error) {
	out := new(UpdateRegionResponse)
	err := c.cc.Invoke(ctx, "/region.Region/ClientUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionClient) AddFoods(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/region.Region/AddFoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionClient) RemoveFoods(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/region.Region/RemoveFoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegionServer is the server API for Region service.
type RegionServer interface {
	Ping(context.Context, *EmptyRequest) (*EmptyResponse, error)
	AddRegion(context.Context, *AddRegionRequest) (*EmptyResponse, error)
	GetRegion(context.Context, *IdRegionRequest) (*GetRegionResponse, error)
	RemoveRegion(context.Context, *IdRegionRequest) (*EmptyResponse, error)
	ClientUpdate(context.Context, *UpdateRegionRequest) (*UpdateRegionResponse, error)
	AddFoods(context.Context, *FoodRequest) (*EmptyResponse, error)
	RemoveFoods(context.Context, *FoodRequest) (*EmptyResponse, error)
}

// UnimplementedRegionServer can be embedded to have forward compatible implementations.
type UnimplementedRegionServer struct {
}

func (*UnimplementedRegionServer) Ping(ctx context.Context, req *EmptyRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedRegionServer) AddRegion(ctx context.Context, req *AddRegionRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRegion not implemented")
}
func (*UnimplementedRegionServer) GetRegion(ctx context.Context, req *IdRegionRequest) (*GetRegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegion not implemented")
}
func (*UnimplementedRegionServer) RemoveRegion(ctx context.Context, req *IdRegionRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveRegion not implemented")
}
func (*UnimplementedRegionServer) ClientUpdate(ctx context.Context, req *UpdateRegionRequest) (*UpdateRegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientUpdate not implemented")
}
func (*UnimplementedRegionServer) AddFoods(ctx context.Context, req *FoodRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFoods not implemented")
}
func (*UnimplementedRegionServer) RemoveFoods(ctx context.Context, req *FoodRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFoods not implemented")
}

func RegisterRegionServer(s *grpc.Server, srv RegionServer) {
	s.RegisterService(&_Region_serviceDesc, srv)
}

func _Region_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/region.Region/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServer).Ping(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Region_AddRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServer).AddRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/region.Region/AddRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServer).AddRegion(ctx, req.(*AddRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Region_GetRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServer).GetRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/region.Region/GetRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServer).GetRegion(ctx, req.(*IdRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Region_RemoveRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServer).RemoveRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/region.Region/RemoveRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServer).RemoveRegion(ctx, req.(*IdRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Region_ClientUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServer).ClientUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/region.Region/ClientUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServer).ClientUpdate(ctx, req.(*UpdateRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Region_AddFoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServer).AddFoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/region.Region/AddFoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServer).AddFoods(ctx, req.(*FoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Region_RemoveFoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServer).RemoveFoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/region.Region/RemoveFoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServer).RemoveFoods(ctx, req.(*FoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Region_serviceDesc = grpc.ServiceDesc{
	ServiceName: "region.Region",
	HandlerType: (*RegionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Region_Ping_Handler,
		},
		{
			MethodName: "AddRegion",
			Handler:    _Region_AddRegion_Handler,
		},
		{
			MethodName: "GetRegion",
			Handler:    _Region_GetRegion_Handler,
		},
		{
			MethodName: "RemoveRegion",
			Handler:    _Region_RemoveRegion_Handler,
		},
		{
			MethodName: "ClientUpdate",
			Handler:    _Region_ClientUpdate_Handler,
		},
		{
			MethodName: "AddFoods",
			Handler:    _Region_AddFoods_Handler,
		},
		{
			MethodName: "RemoveFoods",
			Handler:    _Region_RemoveFoods_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "region.proto",
}
