// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entry.proto

package entryserver

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CanStartRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CanStartRequest) Reset()         { *m = CanStartRequest{} }
func (m *CanStartRequest) String() string { return proto.CompactTextString(m) }
func (*CanStartRequest) ProtoMessage()    {}
func (*CanStartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa6c5b6c627940f, []int{0}
}

func (m *CanStartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CanStartRequest.Unmarshal(m, b)
}
func (m *CanStartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CanStartRequest.Marshal(b, m, deterministic)
}
func (m *CanStartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CanStartRequest.Merge(m, src)
}
func (m *CanStartRequest) XXX_Size() int {
	return xxx_messageInfo_CanStartRequest.Size(m)
}
func (m *CanStartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CanStartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CanStartRequest proto.InternalMessageInfo

type JoinRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa6c5b6c627940f, []int{1}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type JoinReply struct {
	Action               string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	MapLength            int32    `protobuf:"varint,3,opt,name=mapLength,proto3" json:"mapLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinReply) Reset()         { *m = JoinReply{} }
func (m *JoinReply) String() string { return proto.CompactTextString(m) }
func (*JoinReply) ProtoMessage()    {}
func (*JoinReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa6c5b6c627940f, []int{2}
}

func (m *JoinReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinReply.Unmarshal(m, b)
}
func (m *JoinReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinReply.Marshal(b, m, deterministic)
}
func (m *JoinReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinReply.Merge(m, src)
}
func (m *JoinReply) XXX_Size() int {
	return xxx_messageInfo_JoinReply.Size(m)
}
func (m *JoinReply) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinReply.DiscardUnknown(m)
}

var xxx_messageInfo_JoinReply proto.InternalMessageInfo

func (m *JoinReply) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *JoinReply) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *JoinReply) GetMapLength() int32 {
	if m != nil {
		return m.MapLength
	}
	return 0
}

type CanStartReply struct {
	CanStart             bool     `protobuf:"varint,1,opt,name=canStart,proto3" json:"canStart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CanStartReply) Reset()         { *m = CanStartReply{} }
func (m *CanStartReply) String() string { return proto.CompactTextString(m) }
func (*CanStartReply) ProtoMessage()    {}
func (*CanStartReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa6c5b6c627940f, []int{3}
}

func (m *CanStartReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CanStartReply.Unmarshal(m, b)
}
func (m *CanStartReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CanStartReply.Marshal(b, m, deterministic)
}
func (m *CanStartReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CanStartReply.Merge(m, src)
}
func (m *CanStartReply) XXX_Size() int {
	return xxx_messageInfo_CanStartReply.Size(m)
}
func (m *CanStartReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CanStartReply.DiscardUnknown(m)
}

var xxx_messageInfo_CanStartReply proto.InternalMessageInfo

func (m *CanStartReply) GetCanStart() bool {
	if m != nil {
		return m.CanStart
	}
	return false
}

func init() {
	proto.RegisterType((*CanStartRequest)(nil), "entryserver.CanStartRequest")
	proto.RegisterType((*JoinRequest)(nil), "entryserver.JoinRequest")
	proto.RegisterType((*JoinReply)(nil), "entryserver.JoinReply")
	proto.RegisterType((*CanStartReply)(nil), "entryserver.CanStartReply")
}

func init() {
	proto.RegisterFile("entry.proto", fileDescriptor_daa6c5b6c627940f)
}

var fileDescriptor_daa6c5b6c627940f = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xcd, 0x2b, 0x29,
	0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x82, 0x70, 0x8a, 0x53, 0x8b, 0xca, 0x52, 0x8b,
	0x94, 0x04, 0xb9, 0xf8, 0x9d, 0x13, 0xf3, 0x82, 0x4b, 0x12, 0x8b, 0x4a, 0x82, 0x52, 0x0b, 0x4b,
	0x53, 0x8b, 0x4b, 0x94, 0x64, 0xb9, 0xb8, 0xbd, 0xf2, 0x33, 0xf3, 0xa0, 0x5c, 0x21, 0x3e, 0x2e,
	0xa6, 0xcc, 0x02, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6, 0xcc, 0x02, 0xa5, 0x40, 0x2e,
	0x4e, 0x88, 0x74, 0x41, 0x4e, 0xa5, 0x90, 0x18, 0x17, 0x5b, 0x62, 0x72, 0x49, 0x66, 0x7e, 0x1e,
	0x54, 0x01, 0x94, 0x07, 0xd5, 0xc4, 0x04, 0xd3, 0x24, 0x24, 0xc3, 0xc5, 0x99, 0x9b, 0x58, 0xe0,
	0x93, 0x9a, 0x97, 0x5e, 0x92, 0x21, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x1a, 0x84, 0x10, 0x50, 0xd2,
	0xe6, 0xe2, 0x45, 0x38, 0x02, 0x64, 0xac, 0x14, 0x17, 0x47, 0x32, 0x54, 0x00, 0x6c, 0x30, 0x47,
	0x10, 0x9c, 0x6f, 0x34, 0x91, 0x91, 0x8b, 0xdb, 0x15, 0xe4, 0x83, 0x60, 0xb0, 0x0f, 0x84, 0xac,
	0xb8, 0x58, 0x40, 0xee, 0x11, 0x92, 0xd0, 0x43, 0xf2, 0x97, 0x1e, 0x92, 0x0f, 0xa4, 0xc4, 0xb0,
	0xc8, 0x14, 0xe4, 0x54, 0x2a, 0x31, 0x08, 0xb9, 0x71, 0x71, 0xc0, 0x2c, 0x16, 0x92, 0x41, 0x51,
	0x85, 0x16, 0x28, 0x52, 0x52, 0x38, 0x64, 0xc1, 0xe6, 0x24, 0xb1, 0x81, 0x43, 0xd6, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x46, 0x7a, 0x84, 0x0b, 0x68, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EntryServerClient is the client API for EntryServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EntryServerClient interface {
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinReply, error)
	CanStart(ctx context.Context, in *CanStartRequest, opts ...grpc.CallOption) (*CanStartReply, error)
}

type entryServerClient struct {
	cc grpc.ClientConnInterface
}

func NewEntryServerClient(cc grpc.ClientConnInterface) EntryServerClient {
	return &entryServerClient{cc}
}

func (c *entryServerClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinReply, error) {
	out := new(JoinReply)
	err := c.cc.Invoke(ctx, "/entryserver.EntryServer/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryServerClient) CanStart(ctx context.Context, in *CanStartRequest, opts ...grpc.CallOption) (*CanStartReply, error) {
	out := new(CanStartReply)
	err := c.cc.Invoke(ctx, "/entryserver.EntryServer/CanStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntryServerServer is the server API for EntryServer service.
type EntryServerServer interface {
	Join(context.Context, *JoinRequest) (*JoinReply, error)
	CanStart(context.Context, *CanStartRequest) (*CanStartReply, error)
}

// UnimplementedEntryServerServer can be embedded to have forward compatible implementations.
type UnimplementedEntryServerServer struct {
}

func (*UnimplementedEntryServerServer) Join(ctx context.Context, req *JoinRequest) (*JoinReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedEntryServerServer) CanStart(ctx context.Context, req *CanStartRequest) (*CanStartReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CanStart not implemented")
}

func RegisterEntryServerServer(s *grpc.Server, srv EntryServerServer) {
	s.RegisterService(&_EntryServer_serviceDesc, srv)
}

func _EntryServer_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryServerServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entryserver.EntryServer/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryServerServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryServer_CanStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryServerServer).CanStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entryserver.EntryServer/CanStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryServerServer).CanStart(ctx, req.(*CanStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EntryServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "entryserver.EntryServer",
	HandlerType: (*EntryServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _EntryServer_Join_Handler,
		},
		{
			MethodName: "CanStart",
			Handler:    _EntryServer_CanStart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entry.proto",
}
